- category: potential
  customVariables: []
  description: Deprecated Subject::doAs for Removal
  effort: 3
  labels:
  - source=openjdk18-
  - source=openjdk
  - capability=openjdk18+
  - capability=openjdk
  - domain=java-upgrade
  - category=deprecated-apis
  - os=windows
  - os=linux
  - target=azure-appservice
  - target=azure-aks
  - target=azure-container-apps
  links:
  - title: Deprecated Subject::doAs for Removal
    url: https://www.oracle.com/java/technologies/javase/18all-relnotes.html#JDK-8267108
  message: |-
    Two javax.security.auth.Subject::doAs methods have been deprecated for removal. This is a part of the ongoing effort to remove Security Manager related APIs.
  ruleID: java-18-deprecate-security-00000
  when:
    java.referenced:
      location: METHOD_CALL
      pattern: javax.security.auth.Subject.doAs