- category: mandatory
  customVariables:
  - name: methodName
    nameOfCaptureGroup: methodName
    pattern: java.lang.SecurityManager.(?P<methodName>(checkAwtEventQueueAccess|checkSystemClipboardAccess|checkTopLevelWindow))?(.*)
  description: Certain methods under `java.lang.SecurityManager` tied to the AWT stack have been removed in Java 11
  effort: 1
  labels:
  - source=openjdk11-
  - source=openjdk
  - capability=openjdk11+
  - capability=openjdk
  - domain=java-upgrade
  - category=deprecated-apis
  - os=windows
  - os=linux
  - target=azure-appservice
  - target=azure-aks
  - target=azure-container-apps
  links:
  - title: Java 11 SecurityManager api
    url: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/SecurityManager.html
  - title: Java 11 AWTPermission api
    url: https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/awt/AWTPermission.html
  message: |-
    Due to modularisation, the methods `java.lang.SecurityManager.checkAwtEventQueueAccess()`,
     `java.lang.SecurityManager.checkSystemClipboardAccess()` and
     `java.lang.SecurityManager.checkTopLevelWindow(java.lang.Object)`
     have been removed, so that the core SecurityManager class does not depend on the AWT stack.

     Replace with a call to `java.lang.SecurityManager.checkPermission(java.security.Permission)` as follows:

     `java.lang.SecurityManager.checkAwtEventQueueAccess()` --> `java.lang.SecurityManager.checkPermission(new AWTPermission("accessEventQueue"))`
     `java.lang.SecurityManager.checkSystemClipboardAccess()` --> `java.lang.SecurityManager.checkPermission(new AWTPermission("accessClipboard"))`
     `java.lang.SecurityManager.checkTopLevelWindow(java.lang.Object) --> java.lang.SecurityManager.checkPermission(new AWTPermission("showWindowWithoutWarningBanner"))`
  ruleID: java-11-deprecate-security-00000
  when:
    java.referenced:
      location: METHOD_CALL
      pattern: java.lang.SecurityManager.(checkAwtEventQueueAccess|checkSystemClipboardAccess|checkTopLevelWindow)
- category: mandatory
  customVariables: []
  description: SecurityManager method java.lang.SecurityManager.checkMemberAccess
    has been removed
  effort: 1
  labels:
  - source=openjdk11-
  - source=openjdk
  - capability=openjdk11+
  - capability=openjdk
  - domain=java-upgrade
  - category=deprecated-apis
  - os=windows
  - os=linux
  - target=azure-appservice
  - target=azure-aks
  - target=azure-container-apps
  links:
  - title: Java 11 SecurityManager api
    url: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/SecurityManager.html
  message: |-
    The implementation of `java.lang.SecurityManager.checkMemberAccess(java.lang.Class, int)` relies on an assumption
     that the caller is at a stack depth of 4, which is not something that can be enforced, making the code error-prone.

     Replace with a call to `java.lang.SecurityManager.checkPermission(new RuntimePermission("accessDeclaredMembers"))`.
  ruleID: java-11-deprecate-security-00001
  when:
    java.referenced:
      location: METHOD_CALL
      pattern: java.lang.SecurityManager.checkMemberAccess