- category: mandatory
  customVariables: []
  description: Removal of com.sun.awt.SecurityWarning Class
  effort: 1
  labels:
  - source=openjdk12-
  - source=openjdk
  - capability=openjdk12+
  - capability=openjdk
  - domain=java-upgrade
  - category=deprecated-apis
  - os=windows
  - os=linux
  - target=azure-appservice
  - target=azure-aks
  - target=azure-container-apps
  links:
  - title: Removal of com.sun.awt.SecurityWarning Class
    url: https://www.oracle.com/java/technologies/javase/12all-relnotes.html#JDK-8210692
  message: |-
    The `com.sun.awt.SecurityWarning` class was deprecated as `forRemoval=true` in JDK 11. This class was unused in the JDK and has been removed in this release.
  ruleID: java-12-deprecate-security-00000
  when:
    or:
    - java.referenced:
        location: IMPORT
        pattern: com.sun.awt.SecurityWarning
