- category: optional
  customVariables: []
  description: Environment variables/system properties
  effort: 1
  labels:
  - konveyor.io/target=azure-spring-apps
  - konveyor.io/target=azure-appservice
  - konveyor.io/target=azure-aks
  - konveyor.io/target=azure-container-apps
  - konveyor.io/source
  - config
  links:
  - title: Azure App Configuration documentation
    url: https://learn.microsoft.com/azure/azure-app-configuration
  - title: Azure Key Vault documentation
    url: https://learn.microsoft.com/azure/key-vault
  - title: Configure per-service secrets and externalized settings
    url: https://learn.microsoft.com/azure/developer/java/migration/migrate-spring-boot-to-azure-spring-apps#configure-per-service-secrets-and-externalized-settings
  message: "The application uses environment variables/system properties.\n To migrate
    a Java application that uses environment variables/system properties to Azure,
    you can follow these recommendations:\n \n * **Identify environment variables
    and system properties**: Review the usage of environment variables and system
    properties and externalize them.\n\n * **Add environment variables in Azure**:
    You can inject any per-service configuration settings into each service as environment
    variables.\n\n * **Define system properties in JVM options**: Any system properties
    that the code depends on will need to be defined in JVM options.\n\n * Consider
    using**Azure App Configuration**: You can also replace the usage of environment
    variables with **Azure App Configuration**. By migrating to Azure App Configuration,
    you can centralize and manage your application's configuration settings, making
    it easier to maintain and update them. Azure App Configuration provides features
    like versioning, dynamic updates, and integration with Azure Key Vault for secure
    storage of sensitive configuration values."
  ruleID: azure-system-config-01000
  when:
    or:
    - java.referenced:
        location: METHOD_CALL
        pattern: java.lang.System.getenv*
    - java.referenced:
        location: METHOD_CALL
        pattern: java.lang.System.getProperty*
    - java.referenced:
        location: METHOD_CALL
        pattern: java.lang.System.setProperty*
    - java.referenced:
        location: METHOD_CALL
        pattern: java.lang.System.setProperties*
