- category: potential
  customVariables: []
  description: Restricted configurations found
  effort: 0
  labels:
  - konveyor.io/source=springboot
  - konveyor.io/target=azure-spring-apps
  links:
  - title: Remove restricted configurations
    url: https://learn.microsoft.com/azure/developer/java/migration/migrate-spring-cloud-to-azure-spring-apps?toc=%2Fazure%2Fspring-apps%2Ftoc.json&bc=%2Fazure%2Fspring-apps%2Fbreadcrumb%2Ftoc.json&pivots=sc-standard-tier#remove-restricted-configurations
  - title: Set up a Config server
    url: https://learn.microsoft.com/azure/spring-apps/how-to-config-server
  - title: Enable Service Registration
    url: https://learn.microsoft.com/azure/spring-apps/how-to-service-registration?pivots=programming-language-java
  message: "The application uses restricted configurations for Azure Spring Apps.\n
    These properties are automatically injected into your application environment
    by Azure Spring Apps to access Config Server and Service Discovery.\n Please remove
    them from your application, including configuration files, config server files,
    command line parameters, Java system attributes, and environment variables.\n\n
    If configured in **configuration files**: they will be ignored and overrided by
    Azure Spring Apps.\n \n If configured in **Config Server files**, **command line
    parameters**, **Java system attribute**, **environment variable**: they need to
    be removed or you might experience conflicts and unexpected behavior."
  ruleID: spring-boot-to-azure-restricted-config-01000
  when:
    or:
    - builtin.filecontent:
        filePattern: .*\.(properties|yaml|yml)
        pattern: (eureka\.client\.(serviceUrl\.defaultZone|service-url\.defaultZone))|(eureka\.client\.tls\.keystore)|(eureka\.instance\.preferIpAddress)|(eureka\.instance\.instance-id)|(server\.port)|(spring\.cloud\.config\.tls\.keystore)|(spring\.config\.import)|(spring\.application\.name)|(spring\.jmx\.enabled)|(management\.endpoints\.jmx\.exposure\.include)
